name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: swift test --enable-code-coverage
  format:
    name: Format
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup format
      run: brew install swiftformat
    - name: Format
      run: swiftformat --config style.swiftformat . --lint
